<?php

/**
 * implements hook_menu
 *
 * Creates a "map" page
 */
function easpd_map_menu () {

  $items['map'] = array(
    'page callback' => 'easpd_map_view',
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * hook_menu's page callback
 *
 * Renders the "map" page
 */
function easpd_map_view () {

  // handy variables
  global $base_url;

  $module_path = drupal_get_path('module', 'easpd_map');
  $images_path = $base_url . '/' . $module_path . '/images';

  // SQL query
  $select = db_select('node', 'n')
    ->fields('n', array('nid', 'sticky', 'created'))
    ->condition('n.type', 'country_page');

  $nids  = $select->execute()->fetchCol();
  $nodes = node_load_multiple($nids);

  // Build page
  drupal_set_title(t("EASPD's Members"));
  drupal_add_js($module_path . '/easpd_map.js', 'file');
  drupal_add_css($module_path . '/easpd_map.css', 'file');

  $image = '<img src="' . $images_path . '/carte.png" width="668" height="560" usemap="#members_map" border="0" />';

  $image = file_get_contents($images_path.'/worldmap_easpd.svg');

  $map = '
<script type="text/javascript">
     (function defer() {
          if (window.jQuery) {';


  foreach ($nodes as $nid => $node) {
    $name = $node->field_easpd_country['und'][0]['value'];
    $title = $node->title;
    $coords = explode('|', $country_coords[$name]);
    $href = url("node/".$nid);

    // Produire le javascript qui s'occupe des liens
    $map .= 'jQuery("#'.$name.'").attr("class", "hovering").html("<title>'.$title.'</title>").click(function () {window.location = "'.$href.'";});';
  }

  $map .= '
          } else {
               setTimeout(function() { defer() }, 50);
          }
     })();
</script>';


  $build['default_message'] = array(
    '#markup' => '<div id="members_map_images">' . $image . '</div>' . $map,
  );
  return $build;
}
